FROM dockerhub.private.wso2.com/wso2is-km:5.1.0

COPY pattern-2/is-keymanager/carbon/ /mnt/wso2/carbon-home/

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2/carbon-home/repository/components/lib/
