FROM dockerhub.private.wso2.com/nginx

COPY pattern-3/nginx-lan2/nginx.conf /etc/nginx/nginx.conf

COPY pattern-3/nginx-lan2/apim.crt /etc/nginx/ssl/
COPY pattern-3/nginx-lan2/apim.key /etc/nginx/ssl/