FROM dockerhub.private.wso2.com/nginx

COPY pattern-3/nginx/nginx.conf /etc/nginx/nginx.conf
COPY pattern-3/nginx/mgt.crt /etc/nginx/ssl/
COPY pattern-3/nginx/mgt.key /etc/nginx/ssl/
COPY pattern-3/nginx/wrk.crt /etc/nginx/ssl/
COPY pattern-3/nginx/wrk.key /etc/nginx/ssl/
