FROM docker.wso2.com/wso2am-analytics:2.0.0

COPY pattern-2/am-analytics/carbon/ /mnt/wso2-artifacts

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2-artifacts/repository/components/lib/
