version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/apim-pattern5-apim_rdbms:2.1.0
    build:
        context: ../
        dockerfile: pattern-5/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  analytics:
    image: docker.wso2.com/apim-pattern5-analytics:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/am-analytics/Dockerfile
    environment:
      - SLEEP=130
    ports:
    - "9448:9444"
  traffic-manager:
    image: docker.wso2.com/apim-pattern5-traffic-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/traffic-manager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9447:9443"
  gateway-manager:
    image: docker.wso2.com/apim-pattern5-gateway-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/gateway-manager/Dockerfile
    environment:
      - SLEEP=130
    ports:
    - "9444:9443"
  gateway-worker-km:
    image: docker.wso2.com/apim-pattern5-gateway-worker-km:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/gateway-worker-km/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
    links:
      - gateway-manager
  store:
    image: docker.wso2.com/apim-pattern5-store:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/store/Dockerfile
    environment:
      - SLEEP=220
    ports:
    - "9446:9443"
  publisher:
    image: docker.wso2.com/apim-pattern5-publisher:2.1.0
    build:
      context: ../
      dockerfile: pattern-5/publisher/Dockerfile
    environment:
      - SLEEP=260
    ports:
      - "9445:9443"
