DROP DATABASE IF EXISTS WSO2AM_STATS_DB;
DROP DATABASE IF EXISTS WSO2AM_BUSINESS_RULES_DB;
DROP DATABASE IF EXISTS WSO2AM_DASHBOARD_DB;
DROP DATABASE IF EXISTS WSO2AM_PERMISSIONS_DB;

CREATE DATABASE WSO2AM_STATS_DB;
CREATE DATABASE WSO2AM_BUSINESS_RULES_DB;
CREATE DATABASE WSO2AM_DASHBOARD_DB;
CREATE DATABASE WSO2AM_PERMISSIONS_DB;

GRANT ALL ON WSO2AM_STATS_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_BUSINESS_RULES_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_DASHBOARD_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_PERMISSIONS_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
