version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/apim-pattern3-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-3/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  analytics:
    image: docker.wso2.com/apim-pattern3-am-analytics:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/am-analytics/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9448:9444"
  traffic-manager:
    image: docker.wso2.com/apim-pattern3-traffic-manager:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/traffic-manager/Dockerfile
    environment:
      - SLEEP=50
    ports:
    - "9447:9443"
  keymanager:
    image: docker.wso2.com/apim-pattern3-keymanager:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/keymanager/Dockerfile
    environment:
      - SLEEP=110
    ports:
    - "9443:9443"
  gateway-manager:
    image: docker.wso2.com/apim-pattern3-gateway-manager:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager/Dockerfile
    environment:
      - SLEEP=150
    ports:
    - "9444:9443"
  gateway-worker:
    image: docker.wso2.com/apim-pattern3-gateway-worker:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker/Dockerfile
    environment:
      - SLEEP=230
    ports:
    - "8280:8280"
    - "8243:8243"
    links:
            - gateway-manager
  store:
    image: docker.wso2.com/apim-pattern3-store:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/store/Dockerfile
    environment:
      - SLEEP=250
    ports:
    - "9446:9443"
  publisher:
    image: docker.wso2.com/apim-pattern3-publisher:2.2.0-SNAPSHOT
    build:
      context: ../
      dockerfile: pattern-3/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"
