DROP DATABASE IF EXISTS WSO2AM_STATS_DB;
DROP DATABASE IF EXISTS WSO2AM_BUSINESS_RULES_DB;
DROP DATABASE IF EXISTS WSO2AM_DASHBOARD_DB;
DROP DATABASE IF EXISTS WSO2AM_PERMISSIONS_DB;

CREATE DATABASE WSO2AM_STATS_DB;
CREATE DATABASE WSO2AM_BUSINESS_RULES_DB;
CREATE DATABASE WSO2AM_DASHBOARD_DB;
CREATE DATABASE WSO2AM_PERMISSIONS_DB;

GRANT ALL ON WSO2AM_STATS_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_BUSINESS_RULES_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_DASHBOARD_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON WSO2AM_PERMISSIONS_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';

USE WSO2AM_STATS_DB;

CREATE TABLE IF NOT EXISTS AM_USAGE_UPLOADED_FILES (
FILE_NAME varchar(255) NOT NULL,
FILE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FILE_PROCESSED tinyint(1) DEFAULT 0,
FILE_CONTENT MEDIUMBLOB DEFAULT NULL,
PRIMARY KEY (FILE_NAME, FILE_TIMESTAMP)
);
