FROM docker.wso2.com/wso2is-as-keymanager:5.3.0

COPY pattern-7/is-key-manager/carbon/ /mnt/wso2-artifacts

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2-artifacts/repository/components/lib/