FROM dockerhub.private.wso2.com/nginx

COPY nginx-dmz/nginx.conf /etc/nginx/nginx.conf
COPY nginx-dmz/mgt.crt /etc/nginx/ssl/
COPY nginx-dmz/mgt.key /etc/nginx/ssl/
COPY nginx-dmz/wrk.crt /etc/nginx/ssl/
COPY nginx-dmz/wrk.key /etc/nginx/ssl/
