FROM dockerhub.private.wso2.com/nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/mgt.crt /etc/nginx/ssl/
COPY nginx/mgt.key /etc/nginx/ssl/
COPY nginx/wrk.crt /etc/nginx/ssl/
COPY nginx/wrk.key /etc/nginx/ssl/
