FROM dockerhub.private.wso2.com/nginx

COPY pattern-6/nginx-dmz/nginx.conf /etc/nginx/nginx.conf
COPY pattern-6/nginx-dmz/mgt.crt /etc/nginx/ssl/
COPY pattern-6/nginx-dmz/mgt.key /etc/nginx/ssl/
COPY pattern-6/nginx-dmz/wrk.crt /etc/nginx/ssl/
COPY pattern-6/nginx-dmz/wrk.key /etc/nginx/ssl/
