FROM wso2am-analytics:2.2.0-SNAPSHOT

COPY pattern-3/am-analytics/carbon/ /home/wso2carbon/wso2-artifacts

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /home/wso2carbon/wso2-artifacts/repository/components/lib/

USER root
