FROM dockerhub.private.wso2.com/nginx

COPY pattern-2/nginx-lan/nginx.conf /etc/nginx/nginx.conf
COPY pattern-2/nginx-lan/mgt.crt /etc/nginx/ssl/
COPY pattern-2/nginx-lan/mgt.key /etc/nginx/ssl/
COPY pattern-2/nginx-lan/wrk.crt /etc/nginx/ssl/
COPY pattern-2/nginx-lan/wrk.key /etc/nginx/ssl/
