FROM dockerhub.private.wso2.com/nginx

COPY pattern-2/nginx-lan/nginx.conf /etc/nginx/nginx.conf
COPY pattern-2/nginx-lan/nginx.crt /etc/nginx/ssl/
COPY pattern-2/nginx-lan/nginx.key /etc/nginx/ssl/

