FROM docker.wso2.com/nginx

COPY pattern-0/nginx/nginx.conf /etc/nginx/nginx.conf
COPY pattern-0/nginx/mgt.crt /etc/nginx/ssl/
COPY pattern-0/nginx/mgt.key /etc/nginx/ssl/
COPY pattern-0/nginx/wrk.crt /etc/nginx/ssl/
COPY pattern-0/nginx/wrk.key /etc/nginx/ssl/
